Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: T-PicoC3 Display 
+name: T-PicoC3 Display + ST7789 + TPicoESPC3 Wifi Module Side RP2040
 
 permissions:
   contents: write
@@ -8,7 +8,7 @@ on:
     tags:
      - 'v*'
   schedule:
-     - cron: '0 0 * * 0'
+     - cron: '0 0 */14 * *'
   
   workflow_dispatch:
 
@@ -118,7 +118,33 @@ jobs:
     - name: Generate Tag
       id: tag
       run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
-      
+
+    - name: Validar archivo T-PicoC3.uf2 por nombre y tamaño
+      run: |
+        TARGET=./artifacts/T-PicoC3.uf2
+        MAX_BYTES=$((2 * 1024 * 1024))  # 2MB
+    
+        if [ ! -f "$TARGET" ]; then
+          echo "::error::El archivo $TARGET no existe."
+          exit 1
+        fi
+    
+        BASENAME=$(basename "$TARGET")
+        if [ "$BASENAME" != "T-PicoC3.uf2" ]; then
+          echo "::error::El archivo tiene un nombre inesperado: $BASENAME"
+          exit 1
+        fi
+    
+        SIZE_BYTES=$(stat -c%s "$TARGET")
+        SIZE_HUMAN=$(du -h "$TARGET" | cut -f1)
+    
+        if [ "$SIZE_BYTES" -gt "$MAX_BYTES" ]; then
+          echo "::error::El archivo $BASENAME es demasiado grande ($SIZE_HUMAN)"
+          exit 1
+        else
+          echo "$BASENAME ok ($SIZE_HUMAN)"
+        fi
+
     - name: GH Release
       uses: softprops/action-gh-release@v2.0.8
       with:
